spring.application.name=auth-service
server.port=8081

#SQL properties
spring.datasource.url=jdbc:mysql://localhost:3306/needle-eye-authdb
spring.datasource.username=root
spring.datasource.password=theenu@1999
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Eureka clint properties
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Kafka config
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false
