spring.application.name=config-service
server.port=8888

# Eureka clint properties
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Config services
spring.cloud.config.server.git.uri=https://github.com/tharusha-theekshana/Needle_Eye_Ecommerce_Project_Configurations
spring.cloud.config.server.git.username=tharusha-theekshana
spring.cloud.config.server.git.password=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
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.search-paths=dev
spring.cloud.config.server.git.clone-on-start=true