spring.application.name=config-service
server.port=8888

# Eureka clint properties
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# .env
spring.config.import=optional:file:.env[.properties]

# Config services
spring.cloud.config.server.git.uri=${GITHUB_URL}
spring.cloud.config.server.git.username=${GITHUB_USERNAME}
spring.cloud.config.server.git.password=${GITHUB_TOKEN}
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.search-paths=${ENVIRONMENT}
spring.cloud.config.server.git.clone-on-start=true